package com.psc.projmaislimpo.telas;
//@author muniz

import javax.swing.JOptionPane;
import javax.swing.*;

public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCadastro = new javax.swing.JLabel();
        LogoCadastro = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        Senha1 = new javax.swing.JLabel();
        Senha2 = new javax.swing.JLabel();
        textSenha1 = new javax.swing.JPasswordField();
        textSenha2 = new javax.swing.JPasswordField();
        Cadastrar = new javax.swing.JButton();
        opcaoCadastro = new javax.swing.JComboBox<>();
        Senha3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Mais Limpo - Cadastro");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        textCadastro.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        textCadastro.setForeground(new java.awt.Color(51, 153, 255));
        textCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textCadastro.setText("Cadastro");

        LogoCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoCadastro.setIcon(new javax.swing.ImageIcon("C:\\Users\\muniz\\OneDrive\\Imagens\\Capturas de tela\\CadastroNovo80x80.png")); // NOI18N

        Email.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(51, 153, 255));
        Email.setText("Digite o seu E-mail");

        textEmail.setBackground(new java.awt.Color(102, 204, 255));
        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });

        Senha1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Senha1.setForeground(new java.awt.Color(51, 153, 255));
        Senha1.setText("Digite a sua Senha");

        Senha2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Senha2.setForeground(new java.awt.Color(51, 153, 255));
        Senha2.setText("Confirme a sua Senha");

        textSenha1.setBackground(new java.awt.Color(102, 204, 255));
        textSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenha1ActionPerformed(evt);
            }
        });

        textSenha2.setBackground(new java.awt.Color(102, 204, 255));
        textSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenha2ActionPerformed(evt);
            }
        });

        Cadastrar.setBackground(new java.awt.Color(102, 204, 255));
        Cadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Cadastrar.setForeground(new java.awt.Color(0, 0, 255));
        Cadastrar.setText("CADASTRAR");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        opcaoCadastro.setBackground(new java.awt.Color(102, 204, 255));
        opcaoCadastro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        opcaoCadastro.setForeground(new java.awt.Color(0, 0, 255));
        opcaoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Voluntário", "ONG" }));
        opcaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoCadastroActionPerformed(evt);
            }
        });

        Senha3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Senha3.setForeground(new java.awt.Color(51, 153, 255));
        Senha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Senha3.setText("Como você deseja ser cadastrado?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(Senha1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Senha2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSenha1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSenha2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Senha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(opcaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Cadastrar)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoCadastro)
                .addGap(18, 18, 18)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Senha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Senha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Senha3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cadastrar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
         // Simular envio e espera de confirmação por e-mail
         //A PARTIR DAQUI É COM VC AMIGÃOO (isso aí embaixo é só pra apresentar, se precisar apagar pra fazer a conexão com alguma coisa, pode apagar, n serve pra nada msm
         
         String email = textEmail.getText();              
        String senha1 = new String(textSenha1.getPassword()); 
        String senha2 = new String(textSenha2.getPassword());

        if (email.isEmpty() || senha1.isEmpty() || senha2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
            return; // Interrompe aqui se estiver vazio
        }
              
        else if (email.equals("teste@email.com") && senha1.equals("123456") && senha2.equals("123456")) {
        // Login correto → abre TelaPrincipal
                     
    JOptionPane.showMessageDialog(this,
        "Esperando confirmação por email...\nSe não receber nada, tente novamente");

    // Criar uma nova thread para simular tempo de espera (não trava a interface)
    new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                // Simula o tempo de espera (ex: 3 segundos)
                Thread.sleep(3000);
            } catch (InterruptedException e) {
            }   // Mostrar confirmação final na thread de interface (EDT)
            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(TelaCadastro.this, "Cadastro confirmado com sucesso!");
                // Abrir a tela de login
                TelaLogin telaLogin = new TelaLogin();
                telaLogin.setVisible(true);
                // Fechar a tela atual (cadastro)
                dispose();
            });
        }
    }).start();
        
    } else {
        JOptionPane.showMessageDialog(this, "Email ou senha inválidos.");
    }

    }//GEN-LAST:event_CadastrarActionPerformed

    private void opcaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoCadastroActionPerformed

    private void textSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenha2ActionPerformed

    private void textSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenha1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel LogoCadastro;
    private javax.swing.JLabel Senha1;
    private javax.swing.JLabel Senha2;
    private javax.swing.JLabel Senha3;
    private javax.swing.JComboBox<String> opcaoCadastro;
    private javax.swing.JLabel textCadastro;
    private javax.swing.JTextField textEmail;
    private javax.swing.JPasswordField textSenha1;
    private javax.swing.JPasswordField textSenha2;
    // End of variables declaration//GEN-END:variables
}
