/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.psc.projmaislimpo.telas;



/**
 *
 * @author muniz
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {

        initComponents();
        setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botaoPontaDaPraia = new javax.swing.JButton();
        botaoAparecida = new javax.swing.JButton();
        botaoEmbare = new javax.swing.JButton();
        botaoBoqueirao = new javax.swing.JButton();
        botaoGonzaga = new javax.swing.JButton();
        botaoPompeia = new javax.swing.JButton();
        botãoJoseMenino = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Mais Limpo - Tela Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aperte no botão da respectiva praia que você está e faça a sua denúncia!");

        jPanel1.setLayout(null);

        botaoPontaDaPraia.setBackground(new java.awt.Color(181, 165, 153));
        botaoPontaDaPraia.setForeground(new java.awt.Color(0, 0, 0));
        botaoPontaDaPraia.setText("Ponta da Praia");
        botaoPontaDaPraia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPontaDaPraiaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoPontaDaPraia);
        botaoPontaDaPraia.setBounds(860, 390, 120, 23);

        botaoAparecida.setBackground(new java.awt.Color(181, 165, 153));
        botaoAparecida.setForeground(new java.awt.Color(0, 0, 0));
        botaoAparecida.setText("Aparecida");
        botaoAparecida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAparecidaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAparecida);
        botaoAparecida.setBounds(790, 290, 90, 23);

        botaoEmbare.setBackground(new java.awt.Color(181, 165, 153));
        botaoEmbare.setForeground(new java.awt.Color(0, 0, 0));
        botaoEmbare.setText("Embaré");
        botaoEmbare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEmbareActionPerformed(evt);
            }
        });
        jPanel1.add(botaoEmbare);
        botaoEmbare.setBounds(680, 200, 72, 23);

        botaoBoqueirao.setBackground(new java.awt.Color(181, 165, 153));
        botaoBoqueirao.setForeground(new java.awt.Color(0, 0, 0));
        botaoBoqueirao.setText("Boqueirão");
        botaoBoqueirao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBoqueiraoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoBoqueirao);
        botaoBoqueirao.setBounds(550, 120, 90, 23);

        botaoGonzaga.setBackground(new java.awt.Color(181, 165, 153));
        botaoGonzaga.setForeground(new java.awt.Color(0, 0, 0));
        botaoGonzaga.setText("Gonzaga");
        botaoGonzaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGonzagaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGonzaga);
        botaoGonzaga.setBounds(380, 60, 90, 23);

        botaoPompeia.setBackground(new java.awt.Color(181, 165, 153));
        botaoPompeia.setForeground(new java.awt.Color(0, 0, 0));
        botaoPompeia.setText("Pompéia");
        botaoPompeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPompeiaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoPompeia);
        botaoPompeia.setBounds(220, 40, 80, 23);

        botãoJoseMenino.setBackground(new java.awt.Color(181, 165, 153));
        botãoJoseMenino.setForeground(new java.awt.Color(0, 0, 0));
        botãoJoseMenino.setText("José Menino");
        botãoJoseMenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoJoseMeninoActionPerformed(evt);
            }
        });
        jPanel1.add(botãoJoseMenino);
        botãoJoseMenino.setBounds(100, 30, 100, 23);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\muniz\\OneDrive\\Imagens\\Capturas de tela\\Praia1000.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-10, 0, 1020, 450);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\muniz\\Downloads\\Logo+Limpo400-removebg-preview.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPompeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPompeiaActionPerformed
        // TODO add your handling code here:
           TelaDenuncias tela = new TelaDenuncias("Pompéia");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_botaoPompeiaActionPerformed

    private void botaoPontaDaPraiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPontaDaPraiaActionPerformed
        // TODO add your handling code here:
        TelaDenuncias tela = new TelaDenuncias("Ponta da Praia");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_botaoPontaDaPraiaActionPerformed

    private void botaoAparecidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAparecidaActionPerformed
        // TODO add your handling code here:
        TelaDenuncias tela = new TelaDenuncias("Aparecida");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botaoAparecidaActionPerformed

    private void botaoEmbareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEmbareActionPerformed
        // TODO add your handling code here:
        TelaDenuncias tela = new TelaDenuncias("Embaré");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botaoEmbareActionPerformed

    private void botaoBoqueiraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBoqueiraoActionPerformed
        // TODO add your handling code here:
        TelaDenuncias tela = new TelaDenuncias("Boqueirão");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botaoBoqueiraoActionPerformed

    private void botaoGonzagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGonzagaActionPerformed
        // TODO add your handling code here:
        TelaDenuncias tela = new TelaDenuncias("Gonzaga");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botaoGonzagaActionPerformed

    private void botãoJoseMeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoJoseMeninoActionPerformed
        // TODO add your handling code here:
        TelaDenuncias tela = new TelaDenuncias("José Menino");
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botãoJoseMeninoActionPerformed

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAparecida;
    private javax.swing.JButton botaoBoqueirao;
    private javax.swing.JButton botaoEmbare;
    private javax.swing.JButton botaoGonzaga;
    private javax.swing.JButton botaoPompeia;
    private javax.swing.JButton botaoPontaDaPraia;
    private javax.swing.JButton botãoJoseMenino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}