package com.psc.projmaislimpo.telas;


//@author muniz
import java.awt.Color;
import javax.swing.JOptionPane;

public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setSize(422, 450);
        setResizable(false);
        setLocationRelativeTo(null); // Centraliza
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconLogin = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        botaoEntrar = new javax.swing.JButton();
        botaoCadastro = new javax.swing.JButton();
        textCadastro = new javax.swing.JLabel();
        ConhecaNossoProjeto = new javax.swing.JLabel();
        botaoMais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Mais Limpo - Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        IconLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\muniz\\OneDrive\\Imagens\\Capturas de tela\\CadeadoAzul136.png")); // NOI18N
        IconLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Titulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 153, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Bem Vindo ao Projeto +Limpo!");

        Email.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(51, 153, 255));
        Email.setText("E-mail");

        Senha.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Senha.setForeground(new java.awt.Color(51, 153, 255));
        Senha.setText("Senha");

        textEmail.setBackground(new java.awt.Color(102, 204, 255));
        textEmail.setForeground(new java.awt.Color(0, 0, 0));
        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });

        textSenha.setBackground(new java.awt.Color(102, 204, 255));
        textSenha.setForeground(new java.awt.Color(0, 0, 0));
        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });

        botaoEntrar.setBackground(new java.awt.Color(102, 204, 255));
        botaoEntrar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoEntrar.setForeground(new java.awt.Color(0, 0, 255));
        botaoEntrar.setText("ENTRAR");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        botaoCadastro.setBackground(new java.awt.Color(102, 204, 255));
        botaoCadastro.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoCadastro.setForeground(new java.awt.Color(0, 0, 255));
        botaoCadastro.setText("CADASTRO");
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        textCadastro.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        textCadastro.setForeground(new java.awt.Color(51, 153, 255));
        textCadastro.setText("Não possui um login? Cadastre-se!     →");

        ConhecaNossoProjeto.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        ConhecaNossoProjeto.setForeground(new java.awt.Color(51, 153, 255));
        ConhecaNossoProjeto.setText("Conheça mais sobre o nosso projeto! →");

        botaoMais.setBackground(new java.awt.Color(102, 204, 255));
        botaoMais.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoMais.setForeground(new java.awt.Color(0, 0, 255));
        botaoMais.setText("MAIS");
        botaoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Senha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConhecaNossoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IconLogin)
                .addGap(0, 0, 0)
                .addComponent(Email)
                .addGap(5, 5, 5)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Senha)
                .addGap(5, 5, 5)
                .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastro)
                    .addComponent(textCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConhecaNossoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMais))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
// TODO add your handling code here:
        String email = textEmail.getText();              
        String senha = new String(textSenha.getPassword()); 

        if (email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
            return; // Interrompe aqui se estiver vazio
        }
        
        if (email.equals("teste@email.com") && senha.equals("123456")) {
        // Login correto → abre TelaPrincipal
            TelaPrincipal tela = new TelaPrincipal();
            tela.setResizable(false);
            tela.setLocationRelativeTo(null); // Centraliza
            tela.setVisible(true); // Agora pode mostrar
            this.dispose(); // Fecha a tela de login
        
    } else {
        JOptionPane.showMessageDialog(this, "Email ou senha inválidos.");
    }
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        // TODO add your handling code here:
                this.dispose();
        TelaCadastro tela = new TelaCadastro();

        tela.setResizable(false);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);

    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void botaoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMaisActionPerformed
        // TODO add your handling code here:
        TelaDescricao telaDescricao = new TelaDescricao(this);
    telaDescricao.setVisible(true);
    this.setVisible(false);

    }//GEN-LAST:event_botaoMaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConhecaNossoProjeto;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel IconLogin;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoMais;
    private javax.swing.JLabel textCadastro;
    private javax.swing.JTextField textEmail;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables
}