package com.psc.projmaislimpo.telas;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import com.psc.projmaislimpo.telas.TelaPrincipal;
import java.awt.Color;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author muniz
 */
public class TelaDenuncias extends javax.swing.JFrame {

    private String nomePraia;
    /**
     * Creates new form Denuncias
     */
    public TelaDenuncias(String nomePraia) {

        this.nomePraia = nomePraia;
        initComponents();
        labelPraia.setText("Praia selecionada: " + nomePraia);
        setLocationRelativeTo(null); // Centraliza a janela
        setResizable(false);
        getContentPane().setBackground(Color.WHITE);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPraia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDenuncia = new javax.swing.JTextArea();
        botaoEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Mais Limpo - Denúncias");
        setBackground(new java.awt.Color(255, 255, 255));

        labelPraia.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelPraia.setForeground(new java.awt.Color(0, 0, 255));
        labelPraia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPraia.setText("Praia:");

        jTextAreaDenuncia.setBackground(new java.awt.Color(153, 255, 255));
        jTextAreaDenuncia.setColumns(20);
        jTextAreaDenuncia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextAreaDenuncia.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaDenuncia.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDenuncia);

        botaoEnviar.setBackground(new java.awt.Color(102, 204, 255));
        botaoEnviar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoEnviar.setForeground(new java.awt.Color(0, 0, 255));
        botaoEnviar.setText("Enviar denúncia");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digite a sua denúncia abaixo:");

        botaoVoltar.setBackground(new java.awt.Color(102, 204, 255));
        botaoVoltar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(0, 0, 255));
        botaoVoltar.setText("Voltar à Tela Principal");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPraia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelPraia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        // TODO add your handling code here:
        String denuncia = jTextAreaDenuncia.getText().trim();
        if (denuncia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite sua denúncia antes de enviar.");
            return;
    }//GEN-LAST:event_botaoEnviarActionPerformed

            System.out.println("Denúncia registrada:");
        System.out.println("Praia: " + nomePraia);
        System.out.println("Texto: " + denuncia);

        JOptionPane.showMessageDialog(this, "Denúncia enviada com sucesso!\nMuito obrigado por fazer a sua denúnica e nos apoiar nesse projeto!");

        // Limpar o campo
        jTextAreaDenuncia.setText("");
}
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Fecha a tela atual
        new TelaPrincipal().setVisible(true); // Abre a tela principal novamente
    }//GEN-LAST:event_botaoVoltarActionPerformed

    
    

    /**
     * @param args the command line arguments
     */
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JToggleButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDenuncia;
    private javax.swing.JLabel labelPraia;
    // End of variables declaration//GEN-END:variables

}